spring.application.name:
spring.profiles.active: local

spring:
  config:
    import:
      - logging.yml
      - storage-rdb.yml
      - client-example.yml
---
spring.config.activate.on-profile: local


---
spring.config.activate.on-profile: local-dev


---
spring.config.activate.on-profile: dev


---
spring.config.activate.on-profile: staging


---
spring.config.activate.on-profile: live
